services:
  db:
    image: postgres:16
    container_name: pg_cafe_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cafe_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

api:
    build: .
    container_name: django_api_container
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=""
      - DB_NAME=cafe_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - db
    command: >
      sh -c "uv run python manage.py migrate &&
             uv run python manage.py seed_menu_items &&
             uv run python manage.py runserver 0.0.0.0:8000 --settings=config.settings.local"

volumes:
  pg_data: