[project]
name = "cafe-epos"
version = "0.1.0"
description = "A small part of a café's EPOS system."
authors = [
    {name = "MicahGH"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django (>=5.2.6,<6.0.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "dotenv>=0.9.9",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "pre-commit>=4.6.1",
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
]

[tool.black]
line-length = 88
target-version = ["py314"]

[tool.ruff]
line-length = 88
target-version = "py314"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "TD002",
    "TD003",
    "FIX002",

    "COM812",
    "ISC001",

    "D100",
    "D104",
    "D105",
    "D107",

    "CPY001",

    "N999",

    "TC003",
    "TC002",
    "TC001",

    "S101",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pyright]
typeCheckingMode = "strict"

reportMissingTypeStubs = false
reportUnknownMemberType = true
reportUnknownArgumentType = true
reportUnknownVariableType = true
reportUnknownLambdaType = true
reportUnknownParameterType = true

reportUnusedImport = true
reportUnusedVariable = true
reportUnusedFunction = true

pythonVersion = "3.14"
