# Generated by Django 5.2.17 on 2026-08-18 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("unit_price_p", models.PositiveIntegerField()),
                (
                    "vat_rate_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tab",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("table_number", models.PositiveIntegerField()),
                ("covers", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("paid", "Paid")], default="open"
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("subtotal_p", models.PositiveIntegerField(default=0)),
                ("service_charge_p", models.PositiveIntegerField(default=0)),
                ("vat_total_p", models.PositiveIntegerField(default=0)),
                ("total_p", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("client_secret", models.UUIDField()),
                ("payment_intent_id", models.UUIDField()),
                ("amount_p", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="api.tab",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TabItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("qty", models.PositiveIntegerField()),
                ("unit_price_p", models.PositiveIntegerField()),
                (
                    "vat_rate_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("vat_p", models.PositiveIntegerField()),
                ("line_total_p", models.PositiveIntegerField()),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.menuitem"
                    ),
                ),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.tab",
                    ),
                ),
            ],
        ),
    ]
